spring.application.name=Filmes

#servidor TOMCAT (pode ser port=80)
server.port=8080

#configuração do banco de dados
spring.datasource.url = jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=require
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Spring JPA / HIBERNATE
#ddl.auto = update / oq fizermos de alteracao em código? vai alterar direto no banco de dados mesmo direto
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

#Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html